Ignore psql settings from .psqlrc

diff --git a/test/destroy_test_db b/test/destroy_test_db
--- a/test/destroy_test_db
+++ b/test/destroy_test_db
@@ -21,8 +21,14 @@ BASEPATH=$( cd $(dirname $0) ; pwd -P )
 URI=$(echo $1 | cut -d'/' -f1-3)
 DB=$2
 
+PGOPTIONS='-c client_min_messages=WARNING' psql "$URI" -Xq >/dev/null -c 'select rolcreatedb from pg_authid where rolname = current_user;' 2>/dev/null
+if [ $? -ne 0 ]; then
+  echo "ERROR: Please specify the user with 'Create DB' permissions, and ensure that the default database for the username exists."
+  exit 1
+fi
+
 # plpgsql does not like psql variables, easier to pull this part off with bash variables
-PGOPTIONS='-c client_min_messages=WARNING' psql "$URI" -q >/dev/null <<EOF
+PGOPTIONS='-c client_min_messages=WARNING' psql "$URI" -Xq >/dev/null <<EOF
 SELECT pg_terminate_backend(pg_stat_activity.pid)
 FROM pg_stat_activity
 WHERE pg_stat_activity.datname = '$DB'
